"use strict";
import { QueryInterface } from "sequelize";
import crypto from "crypto";

const hashPassword = (plainPassword: string) => {
  const salt = crypto.randomBytes(16).toString("hex");
  const hashed = crypto.scryptSync(plainPassword, salt, 64).toString("hex");
  return `${salt}:${hashed}`;
};

export default {
  up: async (queryInterface: QueryInterface, Sequelize: any) => {
    const passwordHash = hashPassword("Password@123");
    return queryInterface.bulkInsert(
      "Users",
      [
        {
          firstName: "Admin",
          lastName: "System",
          Email: "admin@gmail.com",
          Phone: "0123456789",
          img: "https://example.com/admin.png",
          avatar: "https://example.com/admin.png",
          password: passwordHash,
          role_code: "R1",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "User",
          lastName: "User",
          Email: "staff@gmail.com",
          Phone: "0123456789",
          img: "https://example.com/user.png",
          avatar: "https://example.com/user.png",
          password: passwordHash,
          role_code: "R2",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Customer",
          lastName: "Customer",
          Email: "customer@gmail.com",
          Phone: "0123456789",
          img: "https://example.com/customer.png",
          avatar: "https://example.com/customer.png",
          password: passwordHash,
          role_code: "R3",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Nguyễn",
          lastName: "Văn A",
          Email: "khachhang1@gmail.com",
          Phone: "0900000001",
          img: "https://example.com/customer1.png",
          avatar: "https://example.com/customer1.png",
          password: passwordHash,
          role_code: "R3",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Trần",
          lastName: "Thị B",
          Email: "khachhang2@gmail.com",
          Phone: "0900000002",
          img: "https://example.com/customer2.png",
          avatar: "https://example.com/customer2.png",
          password: passwordHash,
          role_code: "R3",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Lê",
          lastName: "Văn C",
          Email: "khachhang3@gmail.com",
          Phone: "0900000003",
          img: "https://example.com/customer3.png",
          avatar: "https://example.com/customer3.png",
          password: passwordHash,
          role_code: "R3",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Phạm",
          lastName: "Thị D",
          Email: "khachhang4@gmail.com",
          Phone: "0900000004",
          img: "https://example.com/customer4.png",
          avatar: "https://example.com/customer4.png",
          password: passwordHash,
          role_code: "R3",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Hoàng",
          lastName: "Văn E",
          Email: "khachhang5@gmail.com",
          Phone: "0900000005",
          img: "https://example.com/customer5.png",
          avatar: "https://example.com/customer5.png",
          password: passwordHash,
          role_code: "R3",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Vũ",
          lastName: "Thị F",
          Email: "khachhang6@gmail.com",
          Phone: "0900000006",
          img: "https://example.com/customer6.png",
          avatar: "https://example.com/customer6.png",
          password: passwordHash,
          role_code: "R3",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Đặng",
          lastName: "Văn G",
          Email: "khachhang7@gmail.com",
          Phone: "0900000007",
          img: "https://example.com/customer7.png",
          avatar: "https://example.com/customer7.png",
          password: passwordHash,
          role_code: "R3",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Bùi",
          lastName: "Thị H",
          Email: "khachhang8@gmail.com",
          Phone: "0900000008",
          img: "https://example.com/customer8.png",
          avatar: "https://example.com/customer8.png",
          password: passwordHash,
          role_code: "R3",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Đỗ",
          lastName: "Văn I",
          Email: "khachhang9@gmail.com",
          Phone: "0900000009",
          img: "https://example.com/customer9.png",
          avatar: "https://example.com/customer9.png",
          password: passwordHash,
          role_code: "R3",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      { ignoreDuplicates: true } as any,
    );
  },

  down: (queryInterface: QueryInterface, Sequelize: any) => {
    return queryInterface.bulkDelete("Users", {}, {});
  },
};
