"use strict";
import { QueryInterface } from "sequelize";

export default {
  up: async (queryInterface: QueryInterface, Sequelize: any) => {
    return queryInterface.bulkInsert(
      "Users",
      [
        {
          firstName: "Admin",
          lastName: "System",
          Email: "admin@techspa.com",
          Phone: "0123456789",
          img: "https://example.com/admin.png",
          avatar: "https://example.com/admin.png",
          password: "password123", // Trong thực tế nên hash password
          role_code: "R1",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "User",
          lastName: "User",
          Email: "user@techspa.com",
          Phone: "0123456789",
          img: "https://example.com/user.png",
          avatar: "https://example.com/user.png",
          password: "password123", // Trong thực tế nên hash password
          role_code: "R2",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Customer",
          lastName: "Customer",
          Email: "customer@techspa.com",
          Phone: "0123456789",
          img: "https://example.com/customer.png",
          avatar: "https://example.com/customer.png",
          password: "password123", // Trong thực tế nên hash password
          role_code: "R3",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Nguyễn",
          lastName: "Văn A",
          Email: "khachhang1@techspa.com",
          Phone: "0900000001",
          img: "https://example.com/customer1.png",
          avatar: "https://example.com/customer1.png",
          password: "password123",
          role_code: "R3",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Trần",
          lastName: "Thị B",
          Email: "khachhang2@techspa.com",
          Phone: "0900000002",
          img: "https://example.com/customer2.png",
          avatar: "https://example.com/customer2.png",
          password: "password123",
          role_code: "R3",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Lê",
          lastName: "Văn C",
          Email: "khachhang3@techspa.com",
          Phone: "0900000003",
          img: "https://example.com/customer3.png",
          avatar: "https://example.com/customer3.png",
          password: "password123",
          role_code: "R3",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Phạm",
          lastName: "Thị D",
          Email: "khachhang4@techspa.com",
          Phone: "0900000004",
          img: "https://example.com/customer4.png",
          avatar: "https://example.com/customer4.png",
          password: "password123",
          role_code: "R3",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Hoàng",
          lastName: "Văn E",
          Email: "khachhang5@techspa.com",
          Phone: "0900000005",
          img: "https://example.com/customer5.png",
          avatar: "https://example.com/customer5.png",
          password: "password123",
          role_code: "R3",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Vũ",
          lastName: "Thị F",
          Email: "khachhang6@techspa.com",
          Phone: "0900000006",
          img: "https://example.com/customer6.png",
          avatar: "https://example.com/customer6.png",
          password: "password123",
          role_code: "R3",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Đặng",
          lastName: "Văn G",
          Email: "khachhang7@techspa.com",
          Phone: "0900000007",
          img: "https://example.com/customer7.png",
          avatar: "https://example.com/customer7.png",
          password: "password123",
          role_code: "R3",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Bùi",
          lastName: "Thị H",
          Email: "khachhang8@techspa.com",
          Phone: "0900000008",
          img: "https://example.com/customer8.png",
          avatar: "https://example.com/customer8.png",
          password: "password123",
          role_code: "R3",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Đỗ",
          lastName: "Văn I",
          Email: "khachhang9@techspa.com",
          Phone: "0900000009",
          img: "https://example.com/customer9.png",
          avatar: "https://example.com/customer9.png",
          password: "password123",
          role_code: "R3",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      { ignoreDuplicates: true } as any,
    );
  },

  down: (queryInterface: QueryInterface, Sequelize: any) => {
    return queryInterface.bulkDelete("Users", {}, {});
  },
};
