"use strict";

import { QueryInterface } from "sequelize";

export default {
  up: async (queryInterface: QueryInterface, Sequelize: any) => {
    return queryInterface.bulkInsert(
      "blogs",
      [
        {
          title: "Bí quyết skincare cho người mới bắt đầu",
          slug: "bi-quyet-skincare-cho-nguoi-moi-bat-dau",
          desc: "Nếu bạn đang bối rối không biết bắt đầu chăm sóc da từ đâu, hãy đọc bài viết này để nắm các bước cơ bản nhất.",
          content: "<p>Skincare là một hành trình dài cần sự kiên nhẫn. Các bước cơ bản bao gồm: <strong>Làm sạch - Dưỡng ẩm - Chống nắng</strong>.</p><p>Đừng quá tham lam sử dụng nhiều sản phẩm đặc trị cùng lúc khi da bạn chưa quen.</p>",
          image: "https://bizweb.dftvn.net/thumb/1024x1024/100/386/441/articles/skincare-routine-reset.webp",
          category: "Chăm sóc da",
          blog_category_id: 1,
          status: "published",
          views: 152,
          author_id: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: "Top 5 kem chống nắng được yêu thích nhất 2023",
          slug: "top-5-kem-chong-nang-duoc-yeu-thich-nhat-2023",
          desc: "Điểm danh những dòng kem chống nắng đình đám bảo vệ da hoàn hảo mà không gây bết dính.",
          content: "<p>Kem chống nắng là vật bất ly thân của mọi cô gái. Trong bài viết này chúng ta cùng điểm qua La Roche-Posay, Anessa, và Cell Fusion C...</p>",
          image: "https://bizweb.dftvn.net/thumb/1024x1024/100/386/441/articles/skincare-routine-reset.webp",
          category: "Tư vấn",
          blog_category_id: 3,
          status: "published",
          views: 340,
          author_id: 2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: "Routine trị mụn cho da dầu: 5 bước dễ áp dụng",
          slug: "routine-tri-mun-cho-da-dau-5-buoc-de-ap-dung",
          desc: "Gợi ý routine trị mụn cho da dầu, tập trung làm sạch, phục hồi và chống nắng.",
          content: "<p>Da dầu dễ bít tắc lỗ chân lông nên cần làm sạch đúng cách, kết hợp hoạt chất phù hợp và phục hồi hàng rào da.</p>",
          image: "https://bizweb.dftvn.net/thumb/1024x1024/100/386/441/articles/skincare-routine-reset.webp",
          category: "Trị mụn",
          blog_category_id: 6,
          status: "published",
          views: 120,
          author_id: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: "Niacinamide là gì? Cách dùng đúng để giảm dầu mờ thâm",
          slug: "niacinamide-la-gi-cach-dung-dung-de-giam-dau-mo-tham",
          desc: "Niacinamide là hoạt chất đa năng hỗ trợ giảm dầu, mờ thâm và cải thiện lỗ chân lông.",
          content: "<p>Niacinamide phù hợp nhiều loại da. Nên bắt đầu từ nồng độ thấp và test trước khi dùng toàn mặt.</p>",
          image: "https://bizweb.dftvn.net/thumb/1024x1024/100/386/441/articles/skincare-routine-reset.webp",
          category: "Chăm sóc da",
          blog_category_id: 1,
          status: "published",
          views: 95,
          author_id: 2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: "Review toner cấp ẩm: chọn loại nào cho da khô?",
          slug: "review-toner-cap-am-chon-loai-nao-cho-da-kho",
          desc: "Tổng hợp các tiêu chí chọn toner cấp ẩm phù hợp cho da khô và nhạy cảm.",
          content: "<p>Ưu tiên toner không cồn, chứa HA, panthenol và chiết xuất làm dịu.</p>",
          image: "https://bizweb.dftvn.net/thumb/1024x1024/100/386/441/articles/skincare-routine-reset.webp",
          category: "Review",
          blog_category_id: 5,
          status: "published",
          views: 88,
          author_id: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: "Chống lão hóa từ tuổi 25: bắt đầu thế nào cho đúng?",
          slug: "chong-lao-hoa-tu-tuoi-25-bat-dau-the-nao-cho-dung",
          desc: "Gợi ý các bước chống lão hóa đơn giản: chống nắng, dưỡng ẩm, antioxidant và retinoid.",
          content: "<p>Chống lão hóa hiệu quả nhất là chống nắng đều đặn mỗi ngày và duy trì lối sống lành mạnh.</p>",
          image: "https://bizweb.dftvn.net/thumb/1024x1024/100/386/441/articles/skincare-routine-reset.webp",
          category: "Chống lão hóa",
          blog_category_id: 7,
          status: "published",
          views: 160,
          author_id: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: "Makeup nhẹ nhàng đi học/đi làm với 6 sản phẩm cơ bản",
          slug: "makeup-nhe-nhang-di-hoc-di-lam-voi-6-san-pham-co-ban",
          desc: "Chỉ với 6 sản phẩm bạn đã có thể makeup tự nhiên, nhanh gọn mỗi ngày.",
          content: "<p>Gợi ý: kem chống nắng, cushion/kem nền mỏng, phấn phủ, kẻ mày, má hồng và son.</p>",
          image: "https://bizweb.dftvn.net/thumb/1024x1024/100/386/441/articles/skincare-routine-reset.webp",
          category: "Trang điểm",
          blog_category_id: 2,
          status: "published",
          views: 210,
          author_id: 2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: "Chăm sóc tóc hư tổn: 3 sai lầm thường gặp",
          slug: "cham-soc-toc-hu-ton-3-sai-lam-thuong-gap",
          desc: "Tóc hư tổn do nhiệt/hoá chất cần dưỡng và bảo vệ đúng cách.",
          content: "<p>Hạn chế nhiệt, dùng dầu xả/ủ tóc và serum bảo vệ trước khi sấy.</p>",
          image: "https://bizweb.dftvn.net/thumb/1024x1024/100/386/441/articles/skincare-routine-reset.webp",
          category: "Chăm sóc tóc",
          blog_category_id: 9,
          status: "published",
          views: 77,
          author_id: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: "Body routine trắng sáng: nên bắt đầu từ đâu?",
          slug: "body-routine-trang-sang-nen-bat-dau-tu-dau",
          desc: "Chăm sóc cơ thể đúng cách giúp da đều màu và mềm mịn hơn.",
          content: "<p>Đừng quên tẩy tế bào chết 1-2 lần/tuần và bôi chống nắng cho vùng da hở.</p>",
          image: "https://bizweb.dftvn.net/thumb/1024x1024/100/386/441/articles/skincare-routine-reset.webp",
          category: "Chăm sóc cơ thể",
          blog_category_id: 8,
          status: "published",
          views: 90,
          author_id: 2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: "Giải đáp: Da nhạy cảm có nên dùng AHA/BHA không?",
          slug: "giai-dap-da-nhay-cam-co-nen-dung-aha-bha-khong",
          desc: "Da nhạy cảm vẫn có thể dùng AHA/BHA nếu chọn nồng độ và tần suất phù hợp.",
          content: "<p>Bắt đầu từ nồng độ thấp, dùng 1-2 lần/tuần và ưu tiên phục hồi hàng rào da.</p>",
          image: "https://bizweb.dftvn.net/thumb/1024x1024/100/386/441/articles/skincare-routine-reset.webp",
          category: "Góc tư vấn",
          blog_category_id: 10,
          status: "published",
          views: 65,
          author_id: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
      ],
      { ignoreDuplicates: true } as any,
    );
  },

  down: async (queryInterface: QueryInterface, Sequelize: any) => {
    return queryInterface.bulkDelete("blogs", {}, {});
  },
};
