"use strict";
import { QueryInterface } from "sequelize";

export default {
  up: async (queryInterface: QueryInterface, Sequelize: any) => {
    return queryInterface.bulkInsert(
      "Products",
      [
        {
          id: 1,
          name: "Sữa rửa mặt hoa hồng",
          description: "Sữa rửa mặt dịu nhẹ chiết xuất từ hoa hồng thiên nhiên giúp làm sạch sâu mà không gây khô da.",
          usage: "Sử dụng 2 lần mỗi ngày, sáng và tối. Lấy một lượng nhỏ tạo bọt và massage nhẹ nhàng trên da mặt.",
          price: 250000,
          discountPrice: 199000,
          image: "https://res.cloudinary.com/demo/image/upload/v1631234571/rose_cleanser.jpg",
          images: JSON.stringify([
            "https://res.cloudinary.com/demo/image/upload/v1631234571/rose_cleanser_1.jpg",
            "https://res.cloudinary.com/demo/image/upload/v1631234571/rose_cleanser_2.jpg"
          ]),
          stock: 50,
          categoryId: 1,
          brand: "BeautyCare Natural",
          status: "active",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 2,
          name: "Serum Vitamin C",
          description: "Serum làm sáng da, mờ thâm nám và chống lão hóa hiệu quả.",
          usage: "Nhỏ 3-4 giọt lên mặt sau khi làm sạch, vỗ nhẹ để tinh chất thẩm thấu.",
          price: 450000,
          discountPrice: 399000,
          image: "https://res.cloudinary.com/demo/image/upload/v1631234572/vit_c_serum.jpg",
          images: JSON.stringify([
            "https://res.cloudinary.com/demo/image/upload/v1631234572/vit_c_serum_1.jpg"
          ]),
          stock: 30,
          categoryId: 1,
          brand: "SkinExpert",
          status: "active",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 3,
          name: "Kem dưỡng thể Oải hương",
          description: "Dưỡng ẩm sâu cho làn da mềm mịn cùng hương thơm oải hương thư giãn.",
          usage: "Thoa đều khắp cơ thể sau khi tắm, đặc biệt là vùng da khô.",
          price: 320000,
          discountPrice: null,
          image: "https://res.cloudinary.com/demo/image/upload/v1631234573/lavender_body_lotion.jpg",
          images: null,
          stock: 100,
          categoryId: 2,
          brand: "BeautyCare Natural",
          status: "active",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 4,
          name: "Tinh dầu Sả chanh",
          description: "Tinh dầu nguyên chất giúp xua đuổi côn trùng và tạo cảm giác tươi mới.",
          usage: "Sử dụng với máy xông tinh dầu hoặc pha loãng để massage.",
          price: 150000,
          discountPrice: 120000,
          image: "https://res.cloudinary.com/demo/image/upload/v1631234574/lemongrass_oil.jpg",
          images: null,
          stock: 80,
          categoryId: 4,
          brand: "SpaZen",
          status: "active",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 5,
          name: "Kem chống nắng Daily UV Shield SPF50+",
          description: "Kem chống nắng nâng tone nhẹ, kiềm dầu và bảo vệ da tối ưu.",
          usage: "Thoa trước khi ra nắng 15-20 phút, thoa lại sau 2-3 giờ.",
          price: 420000,
          discountPrice: 369000,
          image: "https://res.cloudinary.com/demo/image/upload/v1631234581/sunscreen_1.jpg",
          images: null,
          stock: 60,
          categoryId: 5,
          brand: "SunCare",
          status: "active",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 6,
          name: "Toner Cấp Ẩm Hyaluronic",
          description: "Toner cấp ẩm, làm dịu và cân bằng pH cho da.",
          usage: "Dùng sau rửa mặt, vỗ nhẹ lên da hoặc lau bằng bông.",
          price: 280000,
          discountPrice: 239000,
          image: "https://res.cloudinary.com/demo/image/upload/v1631234582/toner_1.jpg",
          images: null,
          stock: 120,
          categoryId: 6,
          brand: "HydraLab",
          status: "active",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 7,
          name: "Mặt nạ giấy Cấp Nước",
          description: "Mặt nạ giấy giúp cấp nước nhanh, da căng mịn.",
          usage: "Đắp 10-15 phút, massage tinh chất còn lại.",
          price: 35000,
          discountPrice: null,
          image: "https://res.cloudinary.com/demo/image/upload/v1631234583/mask_1.jpg",
          images: null,
          stock: 500,
          categoryId: 7,
          brand: "SkinMask",
          status: "active",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 8,
          name: "Dầu gội Phục hồi Keratin",
          description: "Dầu gội giúp phục hồi tóc hư tổn, giảm gãy rụng.",
          usage: "Làm ướt tóc, tạo bọt và massage da đầu 2-3 phút.",
          price: 310000,
          discountPrice: 279000,
          image: "https://res.cloudinary.com/demo/image/upload/v1631234584/shampoo_1.jpg",
          images: null,
          stock: 90,
          categoryId: 8,
          brand: "HairPro",
          status: "active",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 9,
          name: "Bông tẩy trang Cotton 100%",
          description: "Bông tẩy trang mềm mịn, không xơ bông, an toàn cho da.",
          usage: "Dùng với nước tẩy trang/toner theo nhu cầu.",
          price: 45000,
          discountPrice: 39000,
          image: "https://res.cloudinary.com/demo/image/upload/v1631234585/cotton_1.jpg",
          images: null,
          stock: 300,
          categoryId: 9,
          brand: "CottonSoft",
          status: "active",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10,
          name: "Máy xông mặt Mini Spa",
          description: "Máy xông giúp mở lỗ chân lông, hỗ trợ làm sạch sâu.",
          usage: "Đổ nước sạch, xông 5-10 phút, tránh quá gần mặt.",
          price: 650000,
          discountPrice: 599000,
          image: "https://res.cloudinary.com/demo/image/upload/v1631234586/steamer_1.jpg",
          images: null,
          stock: 40,
          categoryId: 10,
          brand: "HomeSpa",
          status: "active",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 11,
          name: "Gel rửa mặt Tràm trà",
          description: "Làm sạch dịu nhẹ, hỗ trợ giảm dầu và mụn.",
          usage: "Dùng sáng/tối, tạo bọt và rửa lại bằng nước.",
          price: 220000,
          discountPrice: 189000,
          image: "https://res.cloudinary.com/demo/image/upload/v1631234587/cleanser_2.jpg",
          images: null,
          stock: 110,
          categoryId: 1,
          brand: "TeaTree Lab",
          status: "active",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 12,
          name: "Serum Niacinamide 10%",
          description: "Hỗ trợ giảm dầu, mờ thâm và se khít lỗ chân lông.",
          usage: "Thoa 2-3 giọt sau toner, dùng sáng/tối.",
          price: 320000,
          discountPrice: 279000,
          image: "https://res.cloudinary.com/demo/image/upload/v1631234588/serum_2.jpg",
          images: null,
          stock: 70,
          categoryId: 1,
          brand: "SkinExpert",
          status: "active",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 13,
          name: "Sữa tắm Hương hoa",
          description: "Sữa tắm dưỡng ẩm, lưu hương nhẹ nhàng.",
          usage: "Lấy lượng vừa đủ, tạo bọt và tắm sạch lại.",
          price: 180000,
          discountPrice: null,
          image: "https://res.cloudinary.com/demo/image/upload/v1631234589/shower_1.jpg",
          images: null,
          stock: 140,
          categoryId: 2,
          brand: "BeautyCare Natural",
          status: "active",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 14,
          name: "Kem dưỡng tay Dưỡng ẩm sâu",
          description: "Kem dưỡng tay giúp mềm mịn, giảm khô ráp.",
          usage: "Thoa lên tay và massage nhẹ nhàng.",
          price: 90000,
          discountPrice: 79000,
          image: "https://res.cloudinary.com/demo/image/upload/v1631234590/handcream_1.jpg",
          images: null,
          stock: 220,
          categoryId: 2,
          brand: "HandCare",
          status: "active",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 15,
          name: "Son tint Lì lâu trôi",
          description: "Son tint lì nhẹ môi, bền màu cả ngày.",
          usage: "Thoa đều lên môi, có thể chồng lớp để đậm màu.",
          price: 260000,
          discountPrice: 229000,
          image: "https://res.cloudinary.com/demo/image/upload/v1631234591/liptint_1.jpg",
          images: null,
          stock: 95,
          categoryId: 3,
          brand: "GlowMake",
          status: "active",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 16,
          name: "Phấn phủ Kiềm dầu",
          description: "Phấn phủ mịn nhẹ, kiềm dầu tốt, không gây bí da.",
          usage: "Dùng cọ/phấn phủ tán đều sau kem nền.",
          price: 310000,
          discountPrice: null,
          image: "https://res.cloudinary.com/demo/image/upload/v1631234592/powder_1.jpg",
          images: null,
          stock: 65,
          categoryId: 3,
          brand: "GlowMake",
          status: "active",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 17,
          name: "Nến thơm Vanilla Relax",
          description: "Nến thơm hương vanilla thư giãn, phù hợp phòng ngủ.",
          usage: "Đốt 1-2 giờ/lần, tránh nơi gió mạnh.",
          price: 240000,
          discountPrice: 199000,
          image: "https://res.cloudinary.com/demo/image/upload/v1631234593/candle_1.jpg",
          images: null,
          stock: 55,
          categoryId: 4,
          brand: "SpaZen",
          status: "active",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 18,
          name: "Tinh dầu Lavender",
          description: "Tinh dầu oải hương giúp ngủ ngon, thư giãn tinh thần.",
          usage: "Nhỏ vài giọt vào máy khuếch tán hoặc pha loãng để massage.",
          price: 190000,
          discountPrice: 169000,
          image: "https://res.cloudinary.com/demo/image/upload/v1631234594/lavender_oil.jpg",
          images: null,
          stock: 75,
          categoryId: 4,
          brand: "SpaZen",
          status: "active",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 19,
          name: "Kem chống nắng Dạng xịt SPF50",
          description: "Chống nắng dạng xịt tiện lợi, phù hợp trang điểm.",
          usage: "Xịt cách mặt 15-20cm, nhắm mắt khi xịt.",
          price: 390000,
          discountPrice: 349000,
          image: "https://res.cloudinary.com/demo/image/upload/v1631234595/sunscreen_2.jpg",
          images: null,
          stock: 50,
          categoryId: 5,
          brand: "SunCare",
          status: "active",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 20,
          name: "Toner Làm dịu Rau má",
          description: "Toner rau má làm dịu da, giảm đỏ rát.",
          usage: "Dùng sáng/tối sau rửa mặt.",
          price: 260000,
          discountPrice: 229000,
          image: "https://res.cloudinary.com/demo/image/upload/v1631234596/toner_2.jpg",
          images: null,
          stock: 100,
          categoryId: 6,
          brand: "CicaCare",
          status: "active",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 21,
          name: "Mặt nạ đất sét Làm sạch",
          description: "Mặt nạ đất sét giúp làm sạch sâu và giảm bã nhờn.",
          usage: "Đắp 10 phút, rửa sạch, dùng 1-2 lần/tuần.",
          price: 320000,
          discountPrice: 279000,
          image: "https://res.cloudinary.com/demo/image/upload/v1631234597/claymask_1.jpg",
          images: null,
          stock: 85,
          categoryId: 7,
          brand: "SkinMask",
          status: "active",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 22,
          name: "Dầu xả Mượt tóc Silk",
          description: "Dầu xả giúp tóc mềm mượt, giảm rối.",
          usage: "Thoa phần thân tóc, ủ 2-3 phút rồi xả sạch.",
          price: 290000,
          discountPrice: null,
          image: "https://res.cloudinary.com/demo/image/upload/v1631234598/conditioner_1.jpg",
          images: null,
          stock: 80,
          categoryId: 8,
          brand: "HairPro",
          status: "active",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 23,
          name: "Cọ tán nền Professional",
          description: "Cọ tán nền lông mềm, tán đều, hạn chế vệt.",
          usage: "Vệ sinh cọ định kỳ 1-2 lần/tuần.",
          price: 180000,
          discountPrice: 149000,
          image: "https://res.cloudinary.com/demo/image/upload/v1631234599/brush_1.jpg",
          images: null,
          stock: 130,
          categoryId: 9,
          brand: "ProTools",
          status: "active",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 24,
          name: "Con lăn Massage đá lạnh",
          description: "Con lăn giúp massage giảm sưng, thư giãn cơ mặt.",
          usage: "Lăn nhẹ theo chiều nâng cơ 3-5 phút.",
          price: 220000,
          discountPrice: 189000,
          image: "https://res.cloudinary.com/demo/image/upload/v1631234600/roller_1.jpg",
          images: null,
          stock: 70,
          categoryId: 10,
          brand: "HomeSpa",
          status: "active",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 25,
          name: "Gel tẩy tế bào chết Dịu nhẹ",
          description: "Tẩy tế bào chết nhẹ nhàng giúp da sáng mịn.",
          usage: "Dùng 1-2 lần/tuần, massage và rửa sạch.",
          price: 260000,
          discountPrice: 219000,
          image: "https://res.cloudinary.com/demo/image/upload/v1631234601/exfoliant_1.jpg",
          images: null,
          stock: 75,
          categoryId: 1,
          brand: "BeautyCare Natural",
          status: "active",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 26,
          name: "Sữa dưỡng thể Dưỡng trắng",
          description: "Dưỡng thể giúp sáng da và cấp ẩm sâu.",
          usage: "Thoa sau khi tắm, tập trung vùng da khô.",
          price: 340000,
          discountPrice: 299000,
          image: "https://res.cloudinary.com/demo/image/upload/v1631234602/bodylotion_2.jpg",
          images: null,
          stock: 95,
          categoryId: 2,
          brand: "BodyCare",
          status: "active",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 27,
          name: "Kem nền Mịn lì",
          description: "Kem nền che phủ tốt, finish mịn lì tự nhiên.",
          usage: "Tán đều bằng mút/cọ sau kem lót.",
          price: 520000,
          discountPrice: 459000,
          image: "https://res.cloudinary.com/demo/image/upload/v1631234603/foundation_1.jpg",
          images: null,
          stock: 40,
          categoryId: 3,
          brand: "GlowMake",
          status: "active",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 28,
          name: "Tinh dầu Bạc hà",
          description: "Tinh dầu bạc hà giúp tỉnh táo, hỗ trợ giảm căng thẳng.",
          usage: "Khuếch tán hoặc pha loãng khi dùng trên da.",
          price: 175000,
          discountPrice: null,
          image: "https://res.cloudinary.com/demo/image/upload/v1631234604/mint_oil.jpg",
          images: null,
          stock: 85,
          categoryId: 4,
          brand: "SpaZen",
          status: "active",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 29,
          name: "Kem chống nắng cho da nhạy cảm",
          description: "Không hương liệu, phù hợp da nhạy cảm, không gây kích ứng.",
          usage: "Thoa đủ lượng và thoa lại định kỳ.",
          price: 460000,
          discountPrice: 399000,
          image: "https://res.cloudinary.com/demo/image/upload/v1631234605/sunscreen_3.jpg",
          images: null,
          stock: 55,
          categoryId: 5,
          brand: "DermCare",
          status: "active",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 30,
          name: "Toner AHA/BHA",
          description: "Hỗ trợ làm sạch lỗ chân lông và cải thiện bề mặt da.",
          usage: "Dùng 2-3 lần/tuần, tránh kết hợp quá nhiều hoạt chất.",
          price: 360000,
          discountPrice: 319000,
          image: "https://res.cloudinary.com/demo/image/upload/v1631234606/toner_3.jpg",
          images: null,
          stock: 60,
          categoryId: 6,
          brand: "AcidLab",
          status: "active",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      { ignoreDuplicates: true } as any
    );
  },

  down: (queryInterface: QueryInterface, Sequelize: any) => {
    return queryInterface.bulkDelete("Products", {}, {});
  },
};
