"use strict";

import { QueryInterface } from "sequelize";

const sampleImages = [
  "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?q=80&w=500&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?q=80&w=500&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1601049541289-9b1b7abc74a4?q=80&w=500&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1615397323141-860882e3895e?q=80&w=500&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1611078489935-0cb964de46d6?q=80&w=500&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1599305090598-fe179d501227?q=80&w=500&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1571781926291-c477ebfd024b?q=80&w=500&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1580870059089-4a00531a74d5?q=80&w=500&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?q=80&w=500&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1631729371254-42c2892f0e6e?q=80&w=500&auto=format&fit=crop"
];

module.exports = {
  up: async (queryInterface: QueryInterface, Sequelize: any) => {
    return queryInterface.bulkInsert("Products", [
      {
        id: 1,
        name: "Nước Tẩy Trang Bioderma Sensibio H2O",
        description: "Nước tẩy trang số 1 toàn cầu, làm sạch sâu, loại bỏ lớp trang điểm, bụi bẩn mà không gây kích ứng.",
        usage: "Thấm nước tẩy trang vào bông cotton, lau nhẹ nhàng toàn bộ khuôn mặt. Không cần rửa lại với nước.",
        price: 495000,
        discountPrice: 420000,
        image: sampleImages[2],
        images: JSON.stringify([sampleImages[2], sampleImages[3]]),
        stock: 200,
        categoryId: 2,
        brand: "Bioderma",
        status: "active",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 2,
        name: "Sữa Rửa Mặt CeraVe Hydrating Facial Cleanser",
        description: "Sữa rửa mặt CeraVe chuyên dành cho da khô và nhạy cảm, giúp làm sạch nhẹ nhàng và cấp ẩm sâu với Hyaluronic Acid và 3 loại Ceramide thiết yếu.",
        usage: "Làm ướt mặt, lấy một lượng vừa đủ tạo bọt và massage nhẹ nhàng. Sau đó rửa sạch lại với nước. Sử dụng sáng và tối.",
        price: 350000,
        discountPrice: 295000,
        image: sampleImages[4],
        images: JSON.stringify([sampleImages[4]]),
        stock: 120,
        categoryId: 1,
        brand: "Cerave",
        status: "active",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 3,
        name: "Serum Phục Hồi Da La Roche-Posay Hyalu B5",
        description: "Tinh chất phục hồi da chuyên sâu, giúp cấp ẩm, làm mờ nếp nhăn và tái tạo hàng rào bảo vệ da mạnh mẽ. Phù hợp cho da nhạy cảm sau mụn.",
        usage: "Sử dụng 3-4 giọt thoa đều lên toàn mặt sau bước làm sạch và dùng toner. Massage nhẹ nhàng để tinh chất thấm sâu.",
        price: 980000,
        discountPrice: 750000,
        image: sampleImages[6],
        images: JSON.stringify([sampleImages[6], sampleImages[7]]),
        stock: 50,
        categoryId: 4,
        brand: "La Roche-Posay",
        status: "active",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 4,
        name: "Kem Chống Nắng Anessa Perfect UV Sunscreen",
        description: "Sữa chống nắng quốc dân bảo vệ da tối đa với công nghệ Auto Booster, chống nước, chống mồ hôi hoàn hảo, thích hợp hoạt động ngoài trời.",
        usage: "Lắc đều trước khi sử dụng. Lấy một lượng vừa đủ thoa đều lên mặt và cổ trước khi ra nắng 20 phút.",
        price: 685000,
        discountPrice: 520000,
        image: sampleImages[5],
        images: JSON.stringify([sampleImages[5]]),
        stock: 300,
        categoryId: 6,
        brand: "Anessa",
        status: "active",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 5,
        name: "Tinh chất tẩy tế bào chết hóa học Paula's Choice 2% BHA",
        description: "Sản phẩm tẩy da chết hóa học nổi tiếng giúp làm sạch sâu lỗ chân lông, đẩy lùi mụn ẩn, mụn đầu đen và cải thiện cấu trúc da hiệu quả.",
        usage: "Dùng 1-2 lần/ngày sau bước sữa rửa mặt và toner. Dùng bông tẩy trang thoa đều hoặc đổ ra tay vỗ nhẹ.",
        price: 950000,
        discountPrice: 850000,
        image: sampleImages[8],
        images: JSON.stringify([sampleImages[8]]),
        stock: 85,
        categoryId: 8,
        brand: "Paula's Choice",
        status: "active",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 6,
        name: "Sữa rửa mặt tạo bọt Senka Perfect Whip",
        description: "Sản phẩm Sữa rửa mặt tạo bọt chính hãng từ thương hiệu Senka. Cung cấp giải pháp tối ưu cho da nhạy cảm.",
        usage: "Làm sạch da mặt, lấy lượng vừa đủ thoa đều lên bề mặt da. Sử dụng đều đặn để phát huy tối đa hiệu quả dưỡng da.",
        price: 990000,
        discountPrice: 594000,
        image: sampleImages[2],
        images: JSON.stringify([sampleImages[2], sampleImages[5]]),
        stock: 147,
        categoryId: 1,
        brand: "Senka",
        status: "active",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 7,
        name: "Sữa chống nắng Vichy kiềm dầu",
        description: "Sản phẩm Sữa chống nắng chính hãng từ thương hiệu Vichy. Cung cấp giải pháp tối ưu cho da mụn.",
        usage: "Làm sạch da mặt, lấy lượng vừa đủ thoa đều lên bề mặt da. Sử dụng đều đặn để phát huy tối đa hiệu quả dưỡng da.",
        price: 620000,
        discountPrice: 558000,
        image: sampleImages[7],
        images: JSON.stringify([sampleImages[7], sampleImages[2]]),
        stock: 153,
        categoryId: 6,
        brand: "Vichy",
        status: "active",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 8,
        name: "Toner cấp ẩm Hada Labo dưỡng sáng da",
        description: "Sản phẩm Toner cấp ẩm chính hãng từ thương hiệu Hada Labo. Cung cấp giải pháp tối ưu dưỡng sáng da.",
        usage: "Làm sạch da mặt, lấy lượng vừa đủ thoa đều lên bề mặt da. Sử dụng đều đặn để phát huy tối đa hiệu quả dưỡng da.",
        price: 590000,
        discountPrice: null,
        image: sampleImages[1],
        images: JSON.stringify([sampleImages[1], sampleImages[7]]),
        stock: 67,
        categoryId: 3,
        brand: "Hada Labo",
        status: "active",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 9,
        name: "Dầu tẩy trang Eucerin cho da mụn",
        description: "Sản phẩm Dầu tẩy trang chính hãng từ thương hiệu Eucerin. Cung cấp giải pháp tối ưu cho da mụn.",
        usage: "Làm sạch da mặt, lấy lượng vừa đủ thoa đều lên bề mặt da. Sử dụng đều đặn để phát huy tối đa hiệu quả dưỡng da.",
        price: 1330000,
        discountPrice: 1197000,
        image: sampleImages[2],
        images: JSON.stringify([sampleImages[2], sampleImages[4]]),
        stock: 122,
        categoryId: 2,
        brand: "Eucerin",
        status: "active",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 10,
        name: "Tinh chất phục hồi COSRX chống lão hóa",
        description: "Sản phẩm Tinh chất phục hồi chính hãng từ thương hiệu COSRX. Cung cấp giải pháp tối ưu chống lão hóa.",
        usage: "Làm sạch da mặt, lấy lượng vừa đủ thoa đều lên bề mặt da. Sử dụng đều đặn để phát huy tối đa hiệu quả dưỡng da.",
        price: 890000,
        discountPrice: 712000,
        image: sampleImages[8],
        images: JSON.stringify([sampleImages[8], sampleImages[0]]),
        stock: 35,
        categoryId: 4,
        brand: "COSRX",
        status: "active",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 11,
        name: "Sữa rửa mặt dịu nhẹ Cetaphil",
        description: "Sản phẩm Sữa rửa mặt dịu nhẹ chính hãng từ thương hiệu Cetaphil. Cung cấp giải pháp tối ưu cho da nhạy cảm.",
        usage: "Làm sạch da mặt, lấy lượng vừa đủ thoa đều lên bề mặt da. Sử dụng đều đặn để phát huy tối đa hiệu quả dưỡng da.",
        price: 1060000,
        discountPrice: 848000,
        image: sampleImages[8],
        images: JSON.stringify([sampleImages[8], sampleImages[2]]),
        stock: 35,
        categoryId: 1,
        brand: "Cetaphil",
        status: "active",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 12,
        name: "Gel dưỡng ẩm Laneige cấp nước",
        description: "Sản phẩm Gel dưỡng ẩm chính hãng từ thương hiệu Laneige. Cung cấp giải pháp tối ưu dành cho mọi loại da.",
        usage: "Làm sạch da mặt, lấy lượng vừa đủ thoa đều lên bề mặt da. Sử dụng đều đặn để phát huy tối đa hiệu quả dưỡng da.",
        price: 520000,
        discountPrice: 416000,
        image: sampleImages[0],
        images: JSON.stringify([sampleImages[0], sampleImages[8]]),
        stock: 129,
        categoryId: 5,
        brand: "Laneige",
        status: "active",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 13,
        name: "Khăn tẩy trang Simple làm sạch sâu",
        description: "Sản phẩm Khăn tẩy trang chính hãng từ thương hiệu Simple. Cung cấp giải pháp tối ưu se khít lỗ chân lông.",
        usage: "Làm sạch da mặt, lấy lượng vừa đủ thoa đều lên bề mặt da. Sử dụng đều đặn để phát huy tối đa hiệu quả dưỡng da.",
        price: 1470000,
        discountPrice: null,
        image: sampleImages[4],
        images: JSON.stringify([sampleImages[4], sampleImages[6]]),
        stock: 28,
        categoryId: 2,
        brand: "Simple",
        status: "active",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 14,
        name: "Mặt nạ ngủ cấp nước Innisfree",
        description: "Sản phẩm Mặt nạ ngủ cấp nước chính hãng từ thương hiệu Innisfree. Cung cấp giải pháp tối ưu cho da khô.",
        usage: "Làm sạch da mặt, lấy lượng vừa đủ thoa đều lên bề mặt da. Sử dụng đều đặn để phát huy tối đa hiệu quả dưỡng da.",
        price: 1210000,
        discountPrice: null,
        image: sampleImages[5],
        images: JSON.stringify([sampleImages[5], sampleImages[2]]),
        stock: 142,
        categoryId: 7,
        brand: "Innisfree",
        status: "active",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 15,
        name: "Kem dưỡng ẩm L'Oreal phục hồi da",
        description: "Sản phẩm Kem dưỡng ẩm chính hãng từ thương hiệu L'Oreal. Cung cấp giải pháp tối ưu phục hồi da.",
        usage: "Làm sạch da mặt, lấy lượng vừa đủ thoa đều lên bề mặt da. Sử dụng đều đặn để phát huy tối đa hiệu quả dưỡng da.",
        price: 640000,
        discountPrice: 448000,
        image: sampleImages[2],
        images: JSON.stringify([sampleImages[2], sampleImages[8]]),
        stock: 110,
        categoryId: 5,
        brand: "L'Oreal",
        status: "active",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 16,
        name: "Sáp tẩy trang làm sạch Garnier",
        description: "Sản phẩm Sáp tẩy trang làm sạch chính hãng từ thương hiệu Garnier. Cung cấp giải pháp tối ưu dành cho mọi loại da.",
        usage: "Làm sạch da mặt, lấy lượng vừa đủ thoa đều lên bề mặt da. Sử dụng đều đặn để phát huy tối đa hiệu quả dưỡng da.",
        price: 210000,
        discountPrice: null,
        image: sampleImages[7],
        images: JSON.stringify([sampleImages[7], sampleImages[6]]),
        stock: 13,
        categoryId: 2,
        brand: "Garnier",
        status: "active",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 17,
        name: "Serum Vitamin C Klairs",
        description: "Sản phẩm Serum Vitamin C chính hãng từ thương hiệu Klairs. Cung cấp giải pháp tối ưu dưỡng sáng da.",
        usage: "Làm sạch da mặt, lấy lượng vừa đủ thoa đều lên bề mặt da. Sử dụng đều đặn để phát huy tối đa hiệu quả dưỡng da.",
        price: 490000,
        discountPrice: null,
        image: sampleImages[5],
        images: JSON.stringify([sampleImages[5], sampleImages[4]]),
        stock: 45,
        categoryId: 4,
        brand: "Klairs",
        status: "active",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 18,
        name: "Toner làm dịu da Some By Mi",
        description: "Sản phẩm Toner làm dịu da chính hãng từ thương hiệu Some By Mi. Cung cấp giải pháp tối ưu kiềm dầu.",
        usage: "Làm sạch da mặt, lấy lượng vừa đủ thoa đều lên bề mặt da. Sử dụng đều đặn để phát huy tối đa hiệu quả dưỡng da.",
        price: 1360000,
        discountPrice: 1088000,
        image: sampleImages[6],
        images: JSON.stringify([sampleImages[6], sampleImages[4]]),
        stock: 147,
        categoryId: 3,
        brand: "Some By Mi",
        status: "active",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 19,
        name: "Gel chống nắng Naruko",
        description: "Sản phẩm Gel chống nắng chính hãng từ thương hiệu Naruko. Cung cấp giải pháp tối ưu cho da mụn.",
        usage: "Làm sạch da mặt, lấy lượng vừa đủ thoa đều lên bề mặt da. Sử dụng đều đặn để phát huy tối đa hiệu quả dưỡng da.",
        price: 260000,
        discountPrice: null,
        image: sampleImages[5],
        images: JSON.stringify([sampleImages[5], sampleImages[4]]),
        stock: 121,
        categoryId: 6,
        brand: "Naruko",
        status: "active",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 20,
        name: "Tẩy da chết vật lý Kiehl's",
        description: "Sản phẩm Tẩy da chết vật lý chính hãng từ thương hiệu Kiehl's. Cung cấp giải pháp tối ưu chống lão hóa.",
        usage: "Làm sạch da mặt, lấy lượng vừa đủ thoa đều lên bề mặt da. Sử dụng đều đặn để phát huy tối đa hiệu quả dưỡng da.",
        price: 1250000,
        discountPrice: 875000,
        image: sampleImages[2],
        images: JSON.stringify([sampleImages[2], sampleImages[5]]),
        stock: 151,
        categoryId: 8,
        brand: "Kiehl's",
        status: "active",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 21,
        name: "Kem chống nắng quang phổ rộng Anessa",
        description: "Sản phẩm Kem chống nắng quang phổ rộng chính hãng từ thương hiệu Anessa. Cung cấp giải pháp tối ưu cho da nhạy cảm.",
        usage: "Làm sạch da mặt, lấy lượng vừa đủ thoa đều lên bề mặt da. Sử dụng đều đặn để phát huy tối đa hiệu quả dưỡng da.",
        price: 380000,
        discountPrice: 342000,
        image: sampleImages[5],
        images: JSON.stringify([sampleImages[5], sampleImages[3]]),
        stock: 124,
        categoryId: 6,
        brand: "Anessa",
        status: "active",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 22,
        name: "Tẩy da chết hóa học Paula's Choice",
        description: "Sản phẩm Tẩy da chết hóa học chính hãng từ thương hiệu Paula's Choice. Cung cấp giải pháp tối ưu kiềm dầu.",
        usage: "Làm sạch da mặt, lấy lượng vừa đủ thoa đều lên bề mặt da. Sử dụng đều đặn để phát huy tối đa hiệu quả dưỡng da.",
        price: 1390000,
        discountPrice: null,
        image: sampleImages[6],
        images: JSON.stringify([sampleImages[6], sampleImages[3]]),
        stock: 104,
        categoryId: 8,
        brand: "Paula's Choice",
        status: "active",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 23,
        name: "Mặt nạ giấy Bioderma",
        description: "Sản phẩm Mặt nạ giấy chính hãng từ thương hiệu Bioderma. Cung cấp giải pháp tối ưu cho da nhạy cảm.",
        usage: "Làm sạch da mặt, lấy lượng vừa đủ thoa đều lên bề mặt da. Sử dụng đều đặn để phát huy tối đa hiệu quả dưỡng da.",
        price: 660000,
        discountPrice: 528000,
        image: sampleImages[6],
        images: JSON.stringify([sampleImages[6], sampleImages[8]]),
        stock: 58,
        categoryId: 7,
        brand: "Bioderma",
        status: "active",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 24,
        name: "Kem phục hồi da La Roche-Posay",
        description: "Sản phẩm Kem phục hồi da chính hãng từ thương hiệu La Roche-Posay. Cung cấp giải pháp tối ưu phục hồi da.",
        usage: "Làm sạch da mặt, lấy lượng vừa đủ thoa đều lên bề mặt da. Sử dụng đều đặn để phát huy tối đa hiệu quả dưỡng da.",
        price: 720000,
        discountPrice: 648000,
        image: sampleImages[5],
        images: JSON.stringify([sampleImages[5], sampleImages[1]]),
        stock: 35,
        categoryId: 5,
        brand: "La Roche-Posay",
        status: "active",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 25,
        name: "Nước tẩy trang L'Oreal",
        description: "Sản phẩm Nước tẩy trang chính hãng từ thương hiệu L'Oreal. Cung cấp giải pháp tối ưu dưỡng sáng da.",
        usage: "Làm sạch da mặt, lấy lượng vừa đủ thoa đều lên bề mặt da. Sử dụng đều đặn để phát huy tối đa hiệu quả dưỡng da.",
        price: 1440000,
        discountPrice: 1008000,
        image: sampleImages[6],
        images: JSON.stringify([sampleImages[6], sampleImages[9]]),
        stock: 153,
        categoryId: 2,
        brand: "L'Oreal",
        status: "active",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 26,
        name: "Sữa rửa mặt dịu nhẹ Vichy",
        description: "Sản phẩm Sữa rửa mặt dịu nhẹ chính hãng từ thương hiệu Vichy. Cung cấp giải pháp tối ưu cho da mụn.",
        usage: "Làm sạch da mặt, lấy lượng vừa đủ thoa đều lên bề mặt da. Sử dụng đều đặn để phát huy tối đa hiệu quả dưỡng da.",
        price: 1250000,
        discountPrice: 875000,
        image: sampleImages[1],
        images: JSON.stringify([sampleImages[1], sampleImages[6]]),
        stock: 112,
        categoryId: 1,
        brand: "Vichy",
        status: "active",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 27,
        name: "Nước hoa hồng Cerave",
        description: "Sản phẩm Nước hoa hồng chính hãng từ thương hiệu Cerave. Cung cấp giải pháp tối ưu phục hồi da.",
        usage: "Làm sạch da mặt, lấy lượng vừa đủ thoa đều lên bề mặt da. Sử dụng đều đặn để phát huy tối đa hiệu quả dưỡng da.",
        price: 450000,
        discountPrice: null,
        image: sampleImages[0],
        images: JSON.stringify([sampleImages[0], sampleImages[7]]),
        stock: 147,
        categoryId: 3,
        brand: "Cerave",
        status: "active",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 28,
        name: "Mặt nạ đất sét giảm mụn Innisfree",
        description: "Sản phẩm Mặt nạ đất sét giảm mụn chính hãng từ thương hiệu Innisfree. Cung cấp giải pháp tối ưu se khít lỗ chân lông.",
        usage: "Làm sạch da mặt, lấy lượng vừa đủ thoa đều lên bề mặt da. Sử dụng đều đặn để phát huy tối đa hiệu quả dưỡng da.",
        price: 1470000,
        discountPrice: null,
        image: sampleImages[8],
        images: JSON.stringify([sampleImages[8], sampleImages[9]]),
        stock: 121,
        categoryId: 7,
        brand: "Innisfree",
        status: "active",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 29,
        name: "Serum trị mụn Eucerin",
        description: "Sản phẩm Serum trị mụn chính hãng từ thương hiệu Eucerin. Cung cấp giải pháp tối ưu cho da mụn.",
        usage: "Làm sạch da mặt, lấy lượng vừa đủ thoa đều lên bề mặt da. Sử dụng đều đặn để phát huy tối đa hiệu quả dưỡng da.",
        price: 930000,
        discountPrice: null,
        image: sampleImages[2],
        images: JSON.stringify([sampleImages[2], sampleImages[0]]),
        stock: 58,
        categoryId: 4,
        brand: "Eucerin",
        status: "active",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 30,
        name: "Toner cấp ẩm Hada Labo",
        description: "Sản phẩm Toner cấp ẩm chính hãng từ thương hiệu Hada Labo. Cung cấp giải pháp tối ưu cho da khô.",
        usage: "Làm sạch da mặt, lấy lượng vừa đủ thoa đều lên bề mặt da. Sử dụng đều đặn để phát huy tối đa hiệu quả dưỡng da.",
        price: 120000,
        discountPrice: 84000,
        image: sampleImages[3],
        images: JSON.stringify([sampleImages[3], sampleImages[5]]),
        stock: 87,
        categoryId: 3,
        brand: "Hada Labo",
        status: "active",
        createdAt: new Date(),
        updatedAt: new Date()
      }
    ]);
  },

  down: async (queryInterface: QueryInterface, Sequelize: any) => {
    return queryInterface.bulkDelete("Products", null, {});
  }
};
